[package]
name = "stevendahfish/fish"
description = "An experiential typed framework for Roblox"
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = ["wally.toml", "default.project.json", ".luaurc", "LICENSE", "src", "src/*"]

[dependencies]
Comm = "sleitnick/comm@^1"
Mutex = "notfenv/mutex@^1"
Signal = "sleitnick/signal@^2"
Promise = "stevendahfish/typed-promise@^4"