[package]
name = "stevendahfish/fish"
description = "An experiential typed framework for Roblox"
version = "1.0.4"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = ["wally.toml", "default.project.json", ".luaurc", "LICENSE", "src", "src/*"]

[dependencies]
Cmdr = "evaera/cmdr@^1"
Comm = "sleitnick/comm@^1"
Signal = "sleitnick/signal@^2"
Promise = "stevendahfish/typed-promise@^4"
TableUtil = "sleitnick/table-util@^1"