[package]
name = "stevendahfish/fish"
description = "An experiential typed framework for Roblox"
version = "1.0.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
t = "osyrisrblx/t@^3"
Comm = "sleitnick/comm@^1"
Promise = "stevendahfish/typed-promise@^4"
TableUtil = "sleitnick/table-util@^1"

[server-dependencies]
Cmdr = "evaera/cmdr@^1"